app_name: "WLJK"

default_host: <%= ENV['DEFAULT_HOST'] %>

bulk_mails:
  default:
    from: 'no-reply@wljk.com'

# Mail settings.
mail:
  address: <%= ENV['MAIL_ADDRESS'] %>
  port: <%= ENV['MAIL_PORT'] %>
  domain: <%= ENV['MAIL_DOMAIN'] %>
  user_name: <%= ENV['MAIL_USER_NAME'] %>
  password: <%= ENV['MAIL_PASSWORD'] %>

redis:
  # http://stackoverflow.com/questions/13770713/starting-sidekiq-on-heroku
  # https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L29-L33
  url: <%= ENV['REDIS_URL'] %>
  namespace: 'wljk'
