<% settings_file_path = Rails.root.to_s + "/config/settings.yml" %>
<%= ERB.new(IO.read(settings_file_path)).result %>

default_host: "localhost:3000"

mail:
  address: 'smtp.gmail.com'
  port: '587'
  domain: 'gmail.com'
  user_name: 'demo.jig@gmail.com'
  password: 'Dem0Jiggi'